# This variant of the base model overrides the training strategy in model.data
#  and isntead canonicalizes both input and output SMILEs.
defaults:
  - pretrain_base_equivariant  # override the model.data section of pretrain_base_equivariant
  - _self_

model:
  data:
    # The following should probably always be True, unless you want to explore the unchanged input data.
    #  Changing will impact val/test metrics since canonicalization is done to model outputs but not
    #  targets (assuming it is done here).
    canonicalize_target_smile: True
    # The following four settings will result in randomized augmentation of SMILES for input, and matched output.
    #  this is the equivarant model case.
    canonicalize_encoder_input: True
    canonicalize_decoder_output: True
    encoder_augment: False
    decoder_independent_augment: False
