# MINIMAL TEST CONFIG for single-node (8 GPU) data ordering verification
#
# This config is for testing that data ordering works correctly
# before running the full 48-GPU job.
#
# Setup:
#   8 GPUs × 1 mbs × 8 grad_acc = 64 GBS
#   2 optimizer steps = 128 samples needed
#
# Usage:
#   # First, dump 128 samples:
#   python scripts/dump_sharded_eden_as_parquet.py \
#       --sequence-db-dir /data/bcr_eden/OG2_database_splits/opengenome2-metagenome \
#       --window-db-path /data/bcr_eden/OG2_database_splits/og2__train__short.sqlite \
#       --output-dir /data/parquet_test \
#       --num-samples 128 \
#       --seed 42
#
#   # Then run training:
#   torchrun --nproc_per_node=8 train_fsdp2.py --config-name L2_og2_parquet_test

defaults:
  - defaults
  - _self_

# Use a tiny model for testing (faster)
config_name_or_path: ./model_configs/llama3-1b-hyena-comparable
config_kwargs:
  vocab_size: 256
  num_hidden_layers: 4  # REDUCED for testing
  hidden_size: 512      # REDUCED for testing
  intermediate_size: 1024
  num_attention_heads: 8
  num_key_value_heads: 8
  max_position_embeddings: 8192
  initializer_range: 0.02
  attn_input_format: bshd
  rope_theta: 500000
  rope_scaling:
    type: "llama3"
    factor: 1
    low_freq_factor: 1
    high_freq_factor: 4
    original_max_position_embeddings: 8192

# Initialization settings
spike_no_more_embedding_init: true
skip_embedding_weight_decay: true
use_megatron_scaled_init: false
use_weight_decay_grouping: true
use_megatron_loss: false

use_sequence_packing: false

# 8 GPUs × 1 mbs × 8 grad_acc = 64 GBS
grad_acc_steps: 8

# Just 2 steps for testing
num_train_steps: 2

wandb:
  name: parquet_test_8gpu
  project: llama3-data-ordering-test
  mode: disabled  # Disable wandb for testing

# Dataset config
dataset:
  tokenizer_name_or_path: ./tokenizers/nucleotide_fast_tokenizer
  micro_batch_size: 1
  num_workers: 2
  prefetch_factor: 2
  max_seq_length: 8192

  load_dataset_kwargs:
    path: parquet
    data_files: /data/parquet_test/*.parquet
    split: train
    streaming: false

  shuffle: false
  skip_tokenization: true
  use_stateful_dataloader: false

  # Enable logging to verify batch composition
  log_sample_indices: true
  sample_log_dir: /data/parquet_sample_logs

# Simple optimizer for testing
adamw_kwargs:
  lr: 1e-04
  fused: true
  betas: [0.9, 0.95]
  eps: 1e-8
  weight_decay: 0.01

lr_scheduler_kwargs:
  num_warmup_steps: 0
  num_decay_steps: 2
  min_lr_ratio: 0.1

# No checkpointing for test
checkpoint:
  ckpt_dir: null
  save_final_model: false
  resume_from_checkpoint: false
  save_every_n_steps: 999999
  async_save: false

logger:
  frequency: 1

profiler:
  enabled: false
