# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: LicenseRef-Apache2

# 7B Llama3 on OpenGenome2 using pre-extracted parquet data from John's logs
# BSHD format (no sequence packing) - matches John's exact data order
#
# This config uses parquet data extracted via parse_window_logs.py to ensure
# we train on the exact same data in the exact same order as John's Megatron run.
#
# Usage:
#   torchrun --nproc_per_node=8 train_fsdp2.py --config-name L2_og2_parquet_test \
#       dataset.load_dataset_kwargs.data_files=/data/savithas/john_data_10k/data_sequential.parquet

defaults:
  - defaults
  - _self_

# 7B model config (matching EdenConfig from bionemo-evo2)
config_name_or_path: meta-llama/Llama-3.1-8B
config_kwargs:
  vocab_size: 256  # CRITICAL: Must match nucleotide tokenizer vocab size!
  num_hidden_layers: 32
  hidden_size: 4096
  intermediate_size: 14336
  num_attention_heads: 32
  num_key_value_heads: 32
  max_position_embeddings: 8192
  initializer_range: 0.02
  attn_input_format: bshd  # BSHD format for parquet data
  rope_theta: 500000
  rope_scaling:
    type: "llama3"
    factor: 1
    low_freq_factor: 1
    high_freq_factor: 4
    original_max_position_embeddings: 8192

# ============ CRITICAL FLAGS TO MATCH JOHN'S RUN ============
spike_no_more_embedding_init: true
skip_embedding_weight_decay: false  # Apply weight decay to embeddings (matches John)
use_weight_decay_grouping: true
use_megatron_scaled_init: true
use_megatron_loss: false
use_meta_device: false
use_fp32_master_weights: false
# ============================================================

use_sequence_packing: false  # BSHD format, no packing

# Gradient accumulation (8 GPUs × 1 mbs × 8 ga = 64 GBS per node)
grad_acc_steps: 8

# Training steps (adjust based on available data)
# 10k steps of data = 10000 * 384 / 64 = 60,000 optimizer steps max for 1 node
num_train_steps: 10000

wandb:
  name: og2_7b_parquet_data_debug
  project: llama3-metagenome-7b
  mode: online

# Dataset config - using pre-dumped parquet from John's logs
dataset:
  tokenizer_name_or_path: ./tokenizers/nucleotide_fast_tokenizer
  micro_batch_size: 1
  num_workers: 4
  prefetch_factor: 2
  max_seq_length: 8192
  stride: 7992

  load_dataset_kwargs:
    path: parquet
    data_files: /data/savithas/john_data_10k/chunks/*.parquet
    split: train
    streaming: false  # CRITICAL: map-style for DistributedSampler

  shuffle: false  # CRITICAL: preserve John's data order
  skip_tokenization: true  # Data is already tokenized
  use_stateful_dataloader: false
  mask_degenerate_bases: true
  uppercase_labels: false

# Optimizer (matching John's settings)
adamw_kwargs:
  lr: 3e-05
  fused: true
  betas: [0.9, 0.95]
  eps: 1e-8
  weight_decay: 0.1

# Learning rate scheduler (matching John's Megatron run)
lr_scheduler_kwargs:
  num_warmup_steps: 2500
  num_decay_steps: 7500  # num_train_steps - warmup
  min_lr_ratio: 0.02

# Validation settings (matching John's val/loss curve)
validation:
  enabled: true
  eval_interval: 500
  num_batches: 40
  data_path: /data/opengenome2/json/pretraining_or_both_phases/metagenomes/data_metagenomics_valid_chunk1.jsonl.gz
  micro_batch_size: 8
  max_seq_length: null
  stride: null

# Checkpoint config
checkpoint:
  ckpt_dir: null
  save_final_model: true
  resume_from_checkpoint: true
  save_every_n_steps: 5000
  async_save: true

logger:
  frequency: 1

profiler:
  enabled: false
