defaults:
  - defaults
  - _self_

model:
  vit:
    img_size: 224
    patch_size: 16
    in_chans: 3
    num_classes: ${dataset.num_classes}
    global_pool: "map"
    embed_dim: 768
    depth: 12
    num_heads: 12
    mlp_ratio: 4.0
    qkv_bias: true
    qk_norm: true
    scale_attn_norm: true
    scale_mlp_norm: true
    proj_bias: true
    init_values: null
    class_token: true
    pos_embed: true
    no_embed_class: false
    reg_tokens: 8
    pre_norm: true
    final_norm: true
    fc_norm: true
    pool_include_prefix: false
    drop_rate: 0.05
    pos_drop_rate: 0.05
    patch_drop_rate: 0.05
    proj_drop_rate: 0.05
    attn_drop_rate: 0.05
    drop_path_rate: 0.05
    weight_init: null
    init_variance_rescale: true
  transformer_engine: false
  channels_last: false

distributed:
  dp_inter: 1
  dp_shard: 1
  cp: 1
  tp: 1

fsdp:
  init_model_with_meta_device: true
  zero_dp_strategy: 3
  fsdp_unit_modules:
    - vit.Block
    - vit.PatchEmbed
    - torch.nn.LayerNorm
    - torch.nn.Linear
  use_hybrid_fsdp: true
  outer_dp_sharding_strategy: 1
  grad_reduce_in_fp32: false
  preserve_fp32_weights: true

training:
  steps: 500
  val_interval: 25
  log_interval: 5
  checkpoint:
    path: "./checkpoints/vit"
    resume_from_metric: "-"   # + = Highest Metric (Score), - = Lowest Metric (Loss)

dataset:
  num_classes: 100000
  num_workers: 4
  train:
    root: "./data/super-tiny-imagenet-5/train"
    class_map: "./data/super-tiny-imagenet-5/words.txt"
    label_map: null   # Not needed, training data is labeled by directory.
    class_filter: null
    batch_size: 5
    shuffle: true
  val:
    root: "./data/super-tiny-imagenet-5/val"
    class_map: "./data/super-tiny-imagenet-5/words.txt"
    label_map: "./data/super-tiny-imagenet-5/val/val_annotations.txt"
    class_filter: null
    batch_size: 5
    shuffle: false

random:
  seed: 42

profiling:
  torch_memory_profile: false
  torch_memory_profile_kwargs:
    max_entries: 250000
  wandb: false
  wandb_kwargs:
    # To use WandB, export WANDB_API_KEY=<your_api_key>!
    name: "bionemo-vit"
    project: "bionemo-recipes"
    dir: null
