defaults:
  - defaults
  - vit_base_patch16_224
  - _self_

model:
  transformer_engine: true

training:
  checkpoint:
    path: "./checkpoints/vit_te"
    resume_from_metric: "-"   # + = Highest Metric (Score), - = Lowest Metric (Loss)

inference:
  checkpoint:
    path: "./checkpoints/vit_te/torch_ckpt_test.pt"
