version: 2

updates:
  - package-ecosystem: "gitsubmodule"
    schedule:
        interval: "weekly"
    directory: "/3rdparty"
    target-branch: "v2-main"
    open-pull-requests-limit: 1
    reviewers:
      - "pstjohn"
      - "jstjohn"
