---
default:
  image: docker:20.10.16
  tags:
    - kamino-prod

stages:
  - build
  - test

services:
  - docker:20.10.16-dind

variables:
  DOCKER_HOST: tcp://docker:2376
  DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"
  DOCKER_TLS_VERIFY: 1
  DOCKER_TLS_CERTDIR: "/certs"
  IMAGE_TAG: "gitlab-master.nvidia.com:5005/clara-discovery/bionemo"
  SHA_TAG: "$IMAGE_TAG:CI_COMMIT_SHA"


build:
  variables:
    LATEST_TAG: "$IMAGE_TAG:$CI_MERGE_REQUEST_TARGET_BRANCH_NAME"
  stage: build
  before_script:
    - until docker info; do sleep 1; done
    - mkdir -p $HOME/.docker
    - echo $DOCKER_AUTH_CONFIG > $HOME/.docker/config.json
  script:
    - docker build --network host --ssh default --no-cache -t $SHA_TAG -f setup/Dockerfile-CI-Only .

push:
  stage: build
  needs:
    - build
  before_script:
    - until docker info; do sleep 1; done
  script:
    - docker push $SHA_TAG
