---
default:
  image: docker:20.10.16


stages:
  - build
  - download
  - test
  - deploy

services:
  - docker:20.10.16-dind

variables:
  NGC_REGISTRY_IMAGE: "nvcr.io/nvidian/clara-lifesciences/bionemo"
  DOCKER_TAG_PREFIX:
    value: "$CI_REGISTRY_IMAGE"
    options:
      - "$CI_REGISTRY_IMAGE"
      - "$NGC_REGISTRY_IMAGE"
    description: "Allows to control wether NGC or gitlab registry is used"
  DOCKER_HOST: tcp://docker:2376
  DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"
  DOCKER_TLS_VERIFY: 1
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_BUILDKIT: 1
  BUILDKIT_PROGRESS: plain
  PIPELINE_TAG: "$DOCKER_TAG_PREFIX:pipeline-$CI_PIPELINE_ID"
  SHA_TAG: "$DOCKER_TAG_PREFIX:$CI_COMMIT_SHORT_SHA-$CI_COMMIT_BRANCH"
  LATEST_TAG: "$DOCKER_TAG_PREFIX:$CI_COMMIT_BRANCH-latest"
  NGC_TAG: "nvcr.io/nvidian/clara-lifesciences/bionemo_ci:latest"
  NEMO_NIGHTLY_TAG: "nvcr.io/nvidian/nemo-nightly:latest-nightly-main"
  NIGHTLY:
    value: "false"
    options:
      - "false"
      - "true"
    description: "Wether to use nightly NeMo docker image as base. Set to 'false' by default."


.docker-setup:
  tags:
    - dind
  before_script:
    - until docker info; do sleep 1; done
    - mkdir -p $HOME/.docker
    - echo $DOCKER_AUTH_CONFIG > $HOME/.docker/config.json


.build-common:
  extends:
    - .docker-setup
  stage: build
  script:
    - if [[ $NIGHTLY = true ]]; then
        base="--build-arg BASE_IMAGE=$NEMO_NIGHTLY_TAG";
      else
        base="";
      fi
    - docker build --network host --no-cache ${base} --label com.nvidia.bionemo.git_hash=${CI_COMMIT_SHORT_SHA}
      -t $PIPELINE_TAG -f setup/Dockerfile .
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $PIPELINE_TAG


build:
  extends:
    - .build-common
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: manual
    - if: $CI_COMMIT_BRANCH == "dev"
    - if: $CI_COMMIT_BRANCH == "main"
    - when: manual


.get-checkpoints:
  image:
    name: "$PIPELINE_TAG"
    entrypoint: [""]
  tags:
    - generic
  stage: download
  variables:
    NGC_CLI_FORMAT_TYPE: ascii
    NGC_CLI_ORG: nvidian
    NGC_CLI_TEAM: clara-lifesciences
    MODEL_PATH: models
  rules:
    - when: on_success
  script:
    - export NGC_CLI_ORG NGC_CLI_TEAM NGC_CLI_FORMAT_TYPE NGC_CLI_API_KEY MODEL_PATH
    - source download_models.sh && download_bionemo_models
  artifacts:
    paths:
      - models
    expire_in: 1 day


.unit-tests-common:
  image:
    name: "$PIPELINE_TAG"
    entrypoint: [""]
  stage: test
  rules:
    - when: on_success
  dependencies:
    - build
    # - get-checkpoints
  # before_script:
  #   - mkdir /model
  #   - cp -r models/* /model
  script:
    - cd /opt/nvidia/bionemo/


unit-test-cpu:
  extends:
    - .unit-tests-common
  tags:
    - cpu
  script:
    - !reference [.unit-tests-common, script]
    - pytest -v -m "not needs_gpu and not needs_checkpoint"


unit-test-gpu:
  extends:
  - .unit-tests-common
  tags:
    - gpu
  script:
    - !reference [.unit-tests-common, script]
    - pytest -v -m "needs_gpu and not needs_checkpoint" -k "not test_model_training"


dev-deploy:
  extends:
    - .docker-setup
  stage: deploy
  rules:
    - if: $CI_COMMIT_BRANCH == "dev" && $NIGHTLY != "true"
    - if: $CI_COMMIT_BRANCH == "main" && $NIGHTLY != "true"
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $PIPELINE_TAG
    - docker tag $PIPELINE_TAG $SHA_TAG
    - docker tag $PIPELINE_TAG $LATEST_TAG
    - docker tag $PIPELINE_TAG $NGC_TAG
    - docker push $SHA_TAG
    - docker push $LATEST_TAG
    - docker push $NGC_TAG
