repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.1
    hooks:
      - id: ruff
        args: ["--fix"] # Attempt to in-place fix issues.
      - id: ruff-format
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
    -   id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        exclude: package.lock.json
  - repo: local
    hooks:
      - id: license-header-check
        name: Run license-check script
        entry: python scripts/license_check.py -c setup.py -c bionemo -c tests -c examples -c internal -c hydra_plugins -c fw2nim_examples -c download_artifacts.py -c docs --modify
        language: python
        additional_dependencies: ["click==8.1.7"]
        pass_filenames: false
        always_run: true
