interfaces = []
exclude = [
    "**/*__pycache__",
    "**/*egg-info",
    "LICENSE",
    "build",
    "docs",
    "tests",
    "venv",
]
source_roots = [
    "sub-packages/bionemo-core/src",
    "sub-packages/bionemo-scdl/src",
    "sub-packages/bionemo-size-aware-batching/src",
    "sub-packages/bionemo-webdatamodule/src",
]

[[modules]]
path = "bionemo.core"
depends_on = []

[[modules]]
path = "bionemo.noodles"
depends_on = [
    "bionemo.core",
]

[[modules]]
path = "bionemo.scdl"
depends_on = [
    "bionemo.core",
]

[[modules]]
path = "bionemo.size_aware_batching"
depends_on = [
    "bionemo.core",
]

[[modules]]
path = "bionemo.webdatamodule"
depends_on = [
    "bionemo.core",
]
