[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "bionemo-webdatamodule"
license.file = "LICENSE"
readme = "README.md"
description = "PyTorch Lightning Data Module for WebDataset files."
authors = [
    { name = "BioNeMo Team", email = "bionemofeedback@nvidia.com" }
]
dynamic = ["dependencies", "version"]

[tool.setuptools.packages.find]
where = ["src"]
include=["bionemo.*"]
namespaces = true
exclude = ["test*."]
