defaults:
  - task/splice_site_prediction

task:
  trainer:
    devices: 1
    val_check_interval: 100
    max_steps: 6000

  model:
    target_name: 'target'
    size: 6000
    data:
      # DO NOT CHANGE, chanbe the container mount rather than the root directory.
      root_directory: ${oc.env:BIONEMO_HOME}/data
      # FIXME move to ${oc.env:BIONEMO_HOME}/data
      dataset_path: ${oc.env:BIONEMO_HOME}/examples/dna/data/splice-site-prediction/sampled-data-30k/
      # Get these paths by running the GRCh38Ensembl99GFF3ResourcePreprocessor in bionemo/data/preprocess/dna/preprocess.py
      train_file: ${oc.env:BIONEMO_HOME}/examples/dna/data/splice-site-prediction/sampled-data-30k/train.csv
      val_file: ${oc.env:BIONEMO_HOME}/examples/dna/data/splice-site-prediction/sampled-data-30k/val.csv
      predict_file: ${oc.env:BIONEMO_HOME}/examples/dna/data/splice-site-prediction/sampled-data-30k/test.csv
      # Ensure the fasta files are the same used to create the GFFs which generate the csvs.
      fasta_directory: ${oc.env:BIONEMO_HOME}/examples/dna/data/splice-site-prediction/GRCh38.ensembl.99
      fasta_pattern: Homo_sapiens.GRCh38.dna.chromosome.{}.fa.gz

      train_perc: .8
      val_perc: .1
      test_perc: .1
    encoder:
      # FIXME make checkpoint available as ${oc.env:BIONEMO_HOME}/models/dna/dnabert/dnabert.nemo
      checkpoint: ${oc.env:BIONEMO_HOME}/models/dna/dnabert/checkpoints/dnabert_k_5_n_12_batchsize_32_minlr_0.0001/dnabert_k_5_n_12_batchsize_32_minlr_0.0001.nemo
