defaults:
  - base_infer_config
  # allow this config to override defaults
  - _self_

hydra:
  searchpath:
     - "${oc.env:BIONEMO_HOME}/examples/conf/"

name: dnabert_inference
desc: Minimum configuration for initializing a DNABERT model for inference.

model:
  downstream_task:
    restore_from_path: "${oc.env:BIONEMO_HOME}/results/nemo_experiments/dnabert/dnabert-dev/dnabert/2023-12-07_21-23-46/checkpoints/dnabert.nemo"
    outputs: [embeddings, hiddens] # Which outputs to extract per sample (a value or list). Possible values: hiddens, embeddings.
  data:
    dataset_path: ???
    batch_size: ???

target: bionemo.model.dna.dnabert.dnabert_model.DNABERTModel # path to model class to load
infer_target: bionemo.model.dna.dnabert.infer.DNABERTInference  # path to inferende class to load
