# @package _global_
defaults:
  - /base
  - _self_

job_name: esm2-recipes
resource_shape: gpu.2xh200

dashboard_info:
  model: esm2_native_te_mfsdp
  variant: recipes
  repo: recipes

# Base configuration
recipe_subdir: esm2_native_te_mfsdp
branch: main
wandb_init_args:
  mode: "online" # need online to collect logs; if offline have to manually sync after run
num_train_steps: 250

# Multiple products to run
products:
  - model_name: nvidia/esm2_t6_8M_UR50D
    train_cmnd: train_mfsdp
    dashboard_info:
      config: 8M-mfsdp

  - model_name: nvidia/esm2_t6_8M_UR50D
    train_cmnd: train_ddp
    dashboard_info:
      config: 8M-ddp

script: |
  git clone https://github.com/NVIDIA/bionemo-framework.git
  if [ "${branch}" != "main" ]; then
    cd bionemo-framework
    git checkout "${branch}"
    cd ..
  fi
  cd bionemo-framework/recipes/${recipe_subdir}
  pip install -r requirements.txt
  torchrun ${train_cmnd}.py \
    --config-name L0_sanity \
    num_train_steps=${num_train_steps} \
    model_name=${model_name} \
    wandb_init_args.mode=${wandb_init_args.mode}
