# @package _global_
defaults:
  - /base
  - _self_

# Base configuration
recipe_subdir: geneformer_native_te_mfsdp_fp8
train_cmnd: train

num_train_steps: 10000

wandb_init_args:
  project: "geneformer_native_te_mfsdp_fp8"

# Run one for each config
products:
  - config: 10m
    resource_shape: gpu.4xh200
  - config: 106m
    resource_shape: gpu.4xh200
  - config: 4b
    resource_shape: gpu.8xh200

train_script: |
  torchrun ${train_cmnd}.py \
    --config-name ${config}.yaml \
    training.num_train_steps=${num_train_steps} \
    wandb_init_args.mode=${wandb_init_args.mode} \
    wandb_init_args.project=${wandb_init_args.project} \
    +wandb_init_args.group=${wandb_init_args.group}
