# @package _global_
defaults:
  - /base
  - _self_

# lepton info
node_group: yo-bom-lepton-001
num_nodes: 1
device_type: gpu
num_devices: 2
gpu_type: h100-sxm
total_gpus: ${multiply:${num_devices},${num_nodes}}
resource_shape: "${device_type}.${num_devices}x${gpu_type}"

# recipe identifiers
recipe_subdir: geneformer_native_te_mfsdp_fp8
model_type: geneformer

# wandb
wandb_init_args:
  project: "test_convergence__recipes__${sanitize:${branch}}"
  group: "${model_type}__${task_cmd}__${total_gpus}__${sanitize:${gpu_type}}"
  job_type: "${recipe_subdir}"
  name: null

# train specific commands
task_cmd: train
num_train_steps: 10

# configs to run
products:
  - config: 10m
    wandb_name: "${config}__${now:%Y%m%d-%H%M%S}__${gitsha:}"
  # - config: 106m
  # - config: 4b

# training script to run
run_script: |
  torchrun ${task_cmd}.py \
    --config-name ${config}.yaml \
    training.num_train_steps=${num_train_steps} \
    wandb_init_args.mode=${wandb_init_args.mode} \
    wandb_init_args.project=${wandb_init_args.project} \
    +wandb_init_args.group=${wandb_init_args.group} \
    +wandb_init_args.job_type=${wandb_init_args.job_type} \
    wandb_init_args.name=${wandb_name}
