defaults:
  - base_infer_config
  # allow this config to override defaults
  - _self_

hydra:
  searchpath:
     - "${oc.env:BIONEMO_HOME}/examples/conf/"

name: geneformer_inference
desc: Minimum configuration for initializing a Geneformer model for inference.

model:
  downstream_task:
    restore_from_path: null # "${oc.env:BIONEMO_HOME}/results/nemo_experiments/geneformer/geneformer-pretraining/geneformer/2024-04-05_02-43-04/checkpoints/geneformer.nemo"
    outputs: [embeddings, hiddens] # Which outputs to extract per sample (a value or list). Possible values: hiddens, embeddings.
  data:
    dataset_path: ???
    batch_size: ???

target: bionemo.model.singlecell.geneformer.model.GeneformerModel # path to model class to load
infer_target: bionemo.model.singlecell.geneformer.infer.GeneformerInference  # path to inferende class to load
