defaults:
  - base_infer_config
  # allow this config to override defaults
  - _self_

hydra:
  searchpath:
     - file://${oc.env:BIONEMO_HOME}/examples/conf/

name: MegaMolBART_Inference
desc: Minimum configuration for initializing a MegaMolBART model for inference.

model:
  callbacks: []  # Set to an empty list to disable model callbacks used during training.
  tokenizer:
    vocab_path: ${oc.env:BIONEMO_HOME}/tokenizers/molecule/megamolbart/vocab/megamolbart.vocab
    model_path: ${oc.env:BIONEMO_HOME}/tokenizers/molecule/megamolbart/vocab/megamolbart.model
  downstream_task:
    #  TODO when retraining this checkpoint, make seq_length: 128 next time for better molecule sampling speed.
    restore_from_path: ${oc.env:BIONEMO_HOME}/models/molecule/megamolbart/megamolbart.nemo
    outputs: [embeddings] # Which outputs to extract per sample (a value or list). Possible values: hiddens, embeddings.
  data:
    # FIXME the following block (before data_fields_map) can be deleted if we train a new megamolbart.nemo model that uses these settings
    # The following should probably always be True, unless you want to explore the unchanged input data.
    #  Changing will impact val/test metrics since canonicalization is done to model outputs but not
    #  targets (assuming it is done here).
    canonicalize_target_smile: True
    # The following four settings will result in randomized augmentation of SMILES for input, and matched output.
    #  this is the equivarant model case.
    canonicalize_encoder_input: False
    canonicalize_decoder_output: False
    encoder_augment: True
    decoder_independent_augment: False
    data_fields_map: # name which data_fields shoud be used for sequence/id (dataset dependant)
      sequence: "smiles"
      id: "iupac"
    dataset_path: ${oc.env:BIONEMO_HOME}/examples/tests/test_data/molecule/physchem/SAMPL/test/x000 # full path to dataset (can include range or a list)

target: bionemo.model.molecule.megamolbart.megamolbart_model.MegaMolBARTModel # path to model class to load
infer_target: bionemo.model.molecule.megamolbart.infer.MegaMolBARTInference # path to inferende class to load
