defaults:
  - pretrain_xsmall_span_aug

model:
  validation:
    validation_enabled: True
    data:
      links_file: ${oc.env:BIONEMO_PATH}/examples/molecule/megamolbart/dataset/PhysChem-downloader.txt
      dataset_path: /data/phys_chem
    datasets:
      - name: ESOL
        class: MLPValidationCallback
        enabled: True
        csv_path: '/data/phys_chem/delaney-processed.csv'
        smis_column: 'smiles'
        target_column: 'measured log solubility in mols per litre'
        num_epochs: 50
        test_fraction: 0.25
        batch_size: 32
        learning_rate: 0.001
        loss_func: MSELoss
        optimizer: Adam
        check_val_every_n_epoch: 10
      - name: FreeSolv
        class: MLPValidationCallback
        enabled: True
        csv_path: '/data/phys_chem/SAMPL.csv'
        smis_column: 'smiles'
        target_column: 'expt'
        num_epochs: 50
        test_fraction: 0.25
        batch_size: 32
        learning_rate: 0.001
        loss_func: MSELoss
        optimizer: Adam
        check_val_every_n_epoch: 10
      - name: Lipophilicity
        class: MLPValidationCallback
        enabled: True
        csv_path: '/data/phys_chem/Lipophilicity.csv'
        smis_column: 'smiles'
        target_column: 'exp'
        num_epochs: 10
        test_fraction: 0.25
        batch_size: 32
        learning_rate: 0.001
        loss_func: MSELoss
        optimizer: Adam
        check_val_every_n_epoch: 10
