extend = "../../../.ruff.toml"

[lint]
# Extend ignores for code ported from MiniFold
ignore = [
    "C901",    # Complexity
    "D100",    # Missing module docstring
    "D101",    # Missing class docstring
    "D102",    # Missing method docstring
    "D103",    # Missing function docstring
    "D105",    # Missing magic method docstring
    "D107",    # Missing __init__ docstring
    "D205",    # 1 blank line required between summary and description
    "D415",    # First line should end with period
    "D417",    # Missing argument descriptions
    "E501",    # Line too long
    "E721",    # Type comparison
    "E731",    # Lambda assignment
    "E741",    # Ambiguous variable name
    "F841",    # Unused variable
    "N806",    # Uppercase variable in function
    "N812",    # Lowercase imported as non-lowercase
    "PLW2901", # Loop variable overwritten
    "RUF005",  # Collection literal concatenation
    "RUF010",  # Explicit f-string conversion
]
