defaults:
  - defaults
  - _self_

model_tag: nvidia/esm2_t36_3B_UR50D

stop_after_n_steps: 10_000

trainer:
  run_name: "esm2_t36_3B_UR50D_perf"
  per_device_train_batch_size: 16
  per_device_eval_batch_size: 16
  report_to: "wandb"
  learning_rate: 4e-4
  weight_decay: 0.01
  warmup_steps: 20_000
