defaults:
  - dnabert_base_config
trainer:
  val_check_interval: 100
model:
  num_layers: 6
  micro_batch_size: 128
  pre_process: True # add embedding
  post_process: True # add pooler
  bert_binary_head: False # BERT binary head
  tokenizer:
    type: 'kmer'
    k: 6
    model: /workspace/bionemo/models/vocab/dnabert/dnabert6-chr1.model
    vocab_file: /workspace/bionemo/models/vocab/dnabert/dnabert6-chr1.vocab
  data:
    dataset_path: /workspace/bionemo/examples/dna/data/small-example # contains train / val / test folders
    dataset: # inclusive range of data files to load or can load a single file, e.g. x000.csv
      train: chr1-trim-train.fna
      test: chr1-trim-test.fna
      val: chr1-trim-val.fna
    micro_batch_size: ${model.micro_batch_size}
    num_workers: 24
    dataloader_type: single
    dataset_format: fasta
