site_name: BioNeMo Framework
site_url: https://docs.nvidia.com/bionemo-framework/
repo_url: https://github.com/NVIDIA/bionemo-fw-ea
repo_name: NVIDIA/bionemo-fw-ea

nav:
  - Home: getting-started/index.md
  - Getting Started:
      - Prerequisites: getting-started/pre-reqs.md
      - Access and Startup: getting-started/access-startup.md
      - Next Steps: getting-started/next-steps.md
  - User Guide: user-guide/index.md
  - Models:
      - Model Benchmarks: models/model-benchmarks.md
      - DiffDock: models/diffdock.md
      - DNABERT: models/dnabert.md
      - DSMBind: models/dsmbind.md
      - EquiDock: models/equidock.md
      - ESM1-NV: models/esm1-nv.md
      - ESM2-NV: models/esm2-nv.md
      - Geneformer: models/geneformer.md
      - MegaMolBART: models/megamolbart.md
      - MolMIM: models/molmim.md
      - OpenFold: models/openfold.md
      - ProtT5-NV: models/prott5nv.md
  - BioNeMo Core:
      - BioNeMo for Model Training: bionemo-core/bionemo-fw-for-model-training-fw.md
      - Data Module: bionemo-core/data-module-fw.md
      - Deep Dive ESM1 PyTriton Inference: bionemo-core/deep-dive-esm1-pytriton-inference.md
      - Downstream Task Validation: bionemo-core/dwnstr-task-validation.md
      - Inference Triton: bionemo-core/inference-triton-fw.md
  - Best Practices:
      - Hyperparameters: best-practices/hyperparameters-fw.md
      - Parallelism: best-practices/parallelism-fw.md
  - Datasets:
      - CELLxGENE: datasets/CELLxGENE.md
      - GRCh38.p13: datasets/GRCh38.p13.md
      - PertNet-2022: datasets/PertNet-2022.md
      - MoleculeNet PhysChem: datasets/moleculenet-physchem.md
      - OpenProteinSet: datasets/openproteinset.md
      - PDB: datasets/pdb.md
      - UniProt: datasets/uniprot.md
      - ZINC15: datasets/zinc15.md
  - Developer Guide:
      - Code Review: developer-guide/CODE-REVIEW.md
      - Contributing: developer-guide/CONTRIBUTING.md
      - Jupyter Notebooks: developer-guide/jupyter-notebooks.ipynb
  - Appendix:
      - FAQ: appendix/faq-fw.md
      - Release Notes: appendix/releasenotes-fw.md
      - Bibliography: appendix/bibliography-fw.md

theme:
  name: "material"
  features:
    - content.code.annotate
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - search.suggest
    - search.highlight
    - content.code.copy
  font:
    text: NVIDIA Sans
    code: Roboto Mono
  favicon: assets/images/favicon.png
  logo: assets/images/logo-white.svg
  language: en
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: nvidia-light
      primary: custom
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: nvidia-dark
      primary: custom
      accent: lime
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference

extra_css:
  - assets/css/color-schemes.css
  - assets/css/fonts.css
  - assets/css/custom-material.css

plugins:
  - search
  - gen-files:
      scripts:
        - scripts/gen_ref_pages.py
  - mkdocstrings:
      handlers:
        python:
          paths:
            - ../sub-packages/*/src
  - mkdocs-jupyter

markdown_extensions:
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.snippets:
      check_paths: true
      restrict_base_path: False
      base_path: "."
  - def_list
  - admonition

copyright: |
  &copy; Copyright 2023-2024 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
