name: openfold

model:
  train_sequence_crop_size: 256
  use_clamped_fape_probability: 0.9
  embed_template_torsion_angles: true
  masked_msa_enabled: true
  masked_msa_profile_prob: 0.1
  masked_msa_replace_fraction: 0.15
  masked_msa_same_prob: 0.1
  masked_msa_uniform_prob: 0.1
  max_distillation_msa_clusters: 1000
  max_extra_msa: 1024
  max_msa_clusters: 124
  max_templates: 4
  msa_cluster_features: true
  num_recycling_iters: 3
  self_distillation_plddt_threshold: 50.0
  shuffle_top_k_prefiltered: 20
  templates_enabled: true

  primary_raw_feature_names:
  - aatype
  - residue_index
  - msa
  - num_alignments
  - seq_length
  - between_segment_residues
  - deletion_matrix

  supervised_raw_features_names:
  - all_atom_mask
  - all_atom_positions
  - resolution
  - is_distillation

  auxiliary_heads_config:

    distogram_head_config:
      c_z: 128
      num_bins: 64
    experimentally_resolved_head_config:
      c_out: 37
      c_s: 384
    masked_msa_head_config:
      c_m: 256
      c_out: 23
    per_residue_lddt_ca_predictor_config:
      c_hidden: 128
      c_s: 384
      num_bins: 50
    tm_score_head_config:
      c_z: 128
      max_bin: 31
      num_bins: 64
    tm_score_head_enabled: false

  evoformer_stack_config:
    c_hidden_msa_att: 32
    c_hidden_opm: 32
    c_hidden_tri_att: 32
    c_hidden_tri_mul: 128
    c_m: 256
    c_s: 384
    c_z: 128
    chunk_size_msa_att: null
    chunk_size_opm: null
    chunk_size_tri_att: null
    eps_opm: 0.001
    inf: 1000000000.0
    msa_dropout: 0.15
    num_blocks: 48
    num_heads_msa: 8
    num_heads_tri: 4
    pair_dropout: 0.25
    transition_n: 4

  extra_msa_embedder_config:
    c_e: 64
    emsa_dim: 25

  extra_msa_stack_config:
    c_e: 64
    c_hidden_msa_att: 8
    c_hidden_opm: 32
    c_hidden_tri_att: 32
    c_hidden_tri_mul: 128
    c_z: 128
    chunk_size_msa_att: null
    chunk_size_opm: null
    chunk_size_tri_att: null
    eps: 1.0e-08
    eps_opm: 0.001
    inf: 1000000000.0
    msa_dropout: 0.15
    num_blocks: 4
    num_heads_msa: 8
    num_heads_tri: 4
    pair_dropout: 0.25
    transition_n: 4

  input_embedder_config:
    c_m: 256
    c_z: 128
    msa_dim: 49
    relpos_k: 32
    tf_dim: 22

  recycling_embedder_config:
    c_m: 256
    c_z: 128
    inf: 100000000.0
    max_bin: 20.75
    min_bin: 3.25
    num_bins: 15

  structure_module_config:
    c_hidden_ang_res: 128
    c_hidden_ipa: 16
    c_s: 384
    c_z: 128
    dropout_rate: 0.1
    eps: 1.0e-08
    inf: 100000.0
    num_ang_res_blocks: 2
    num_angles: 7
    num_blocks: 8
    num_heads_ipa: 12
    num_qk_points: 4
    num_v_points: 8
    scale_factor: 10.0

  template_angle_embedder_config:
    c_m: 256
    ta_dim: 57

  template_pair_embedder_config:
    c_t: 64
    tp_dim: 88

  template_pair_stack_config:
    c_hidden_tri_att: 16
    c_hidden_tri_mul: 64
    c_t: 64
    chunk_size_tri_att: null
    dropout_rate: 0.25
    inf: 1000000000.0
    num_blocks: 2
    num_heads_tri: 4
    pair_transition_n: 2
  template_pointwise_attention_config:
    c_hidden: 16
    c_t: 64
    c_z: 128
    chunk_size: null
    inf: 100000.0
    num_heads: 4
  template_raw_feature_names:
  - template_all_atom_positions
  - template_sum_probs
  - template_aatype
  - template_all_atom_mask

  template_pair_feat_distogram_max_bin: 50.75
  template_pair_feat_distogram_min_bin: 3.25
  template_pair_feat_distogram_num_bins: 39
  template_pair_feat_eps: 1.0e-06
  template_pair_feat_inf: 100000.0
  template_pair_feat_use_unit_vector: false

  loss_config:

    distogram_loss_config:
      eps: 1.0e-08
      max_bin: 21.6875
      min_bin: 2.3125
      num_bins: 64
      weight: 0.3

    experimentally_resolved_loss_config:
      eps: 1.0e-08
      max_resolution: 3.0
      min_resolution: 0.1
      weight: 0.0

    fape_loss_config:
      backbone_clamp_distance: 10.0
      backbone_loss_unit_distance: 10.0
      backbone_weight: 0.5
      eps: 0.0001
      sidechain_clamp_distance: 10.0
      sidechain_length_scale: 10.0
      sidechain_weight: 0.5
      weight: 1.0

    masked_msa_loss_config:
      eps: 1.0e-08
      weight: 2.0

    plddt_loss_config:
      cutoff: 15.0
      eps: 1.0e-08
      max_resolution: 3.0
      min_resolution: 0.1
      num_bins: 50
      weight: 0.01

    supervised_chi_loss_config:
      angle_norm_weight: 0.01
      chi_weight: 0.5
      eps: 1.0e-08
      weight: 1.0

    tm_loss_config:
      enabled: false
      eps: 1.0e-08
      max_bin: 31
      max_resolution: 3.0
      min_resolution: 0.1
      num_bins: 64
      weight: 0.0

    violation_loss_config:
      clash_overlap_tolerance: 1.5
      eps: 1.0e-08
      violation_tolerance_factor: 12.0
      weight: 0.0
