name: "BioNeMo Model Convergence Tests"

on:
  workflow_dispatch:

jobs:
  submit-lepton-jobs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: |
            requirements.ci.txt
            ci/lepton/model_convergence/scripts/requirements.txt

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install "hydra-core==1.3.2" "omegaconf==2.3.0" "leptonai" typer pandas
          python - <<'PY'
          import hydra, omegaconf, leptonai
          print("OK:", hydra.__version__, omegaconf.__version__, leptonai.__version__)
          PY

      - name: Submit Lepton Jobs
        env:
          LEP_LOGIN_CREDENTIALS: ${{ secrets.LEP_LOGIN_CREDENTIALS }}
        run: |
          lep login -c "$LEP_LOGIN_CREDENTIALS" || true
          python ci/lepton/model_convergence/scripts/launch_job.py --config-name "evo2_finetune_lora"
