name: Enforce PR Label for 24.10 release

on:
  pull_request:
    types: [opened, edited, labeled, unlabeled, synchronize, reopened, ready_for_review, review_requested, review_request_removed, auto_merge_enabled, auto_merge_disabled]
    branches:
      - main
      - bionemo1

jobs:
  check-label:
    runs-on: ubuntu-latest
    steps:
      - name: Check for Required Labels
        id: label-check
        run: |
          LABELS=$(jq -r '.pull_request.labels[].name' "$GITHUB_EVENT_PATH")
          if [[ ! "$LABELS" =~ "bug_fix_for_v24.10" ]] && [[ ! "$LABELS" =~ "NOT_related_to_v24.10" ]] && [[ ! "$LABELS" =~ "feature_for_v24.10" ]]; then
            echo "PR does not have the required labels 'bug_fix_for_v24.10' or 'NOT_related_to_v24.10' or 'feature_for_v24.10'"
            exit 1
          fi

      - name: Fail if no required label
        if: failure()
        run: |
          echo "PR cannot be merged without one of the required labels: 'bug_fix_24.10' or 'NOT_related_to_v24.10' or 'feature_for_v24.10'"
          exit 1
