name: pre-commit

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  merge_group:
    types: [checks_requested]
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: 'recursive'
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'
    - run: pip install -r requirements-dev.txt
    - run: ./ci/scripts/static_checks.sh
    - uses: trufflesecurity/trufflehog@main
      with:
        extra_args: --only-verified
