name: SCDL Performance Test

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to use (ignored if commit SHA is provided)"
        required: true
        default: "main"
        type: string
      commit_sha:
        description: "Commit SHA (optional - overrides branch if provided)"
        required: false
        type: string
  schedule:
    - cron: "0 9 * * *" # everyday at 1am PST

jobs:
  submit-lepton-jobs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: |
            ci/lepton/requirements.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ci/lepton/requirements.txt

      - name: Submit SCDL Performance Job
        env:
          LEP_LOGIN_CREDENTIALS: ${{ secrets.LEP_LOGIN_CREDENTIALS }}
          BRANCH: ${{ github.event.inputs.branch        || 'main' }}
          COMMIT_SHA: ${{ github.event.inputs.commit_sha    || '' }}
        run: |
          set -euo pipefail
          lep login -c "$LEP_LOGIN_CREDENTIALS" || true

          python ci/lepton/core/launch_job.py \
            --config-path="../scdl_performance/configs" \
            --config-name="scdl" \
            branch="$BRANCH" \
            commit_sha=$COMMIT_SHA
