name: SCDL Performance Test

on:
  workflow_dispatch:

jobs:
  submit-lepton-jobs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: |
            ci/lepton/scdl_performance/requirements.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ci/lepton/model_convergence/requirements.txt

      - name: Submit SCDL Performance Job
        run: |
          set -euo pipefail
          lep login -c "$LEP_LOGIN_CREDENTIALS" || true

          python launch_job.py \
            --config-path="../../scdl_performance/configs" \
            --config-name="scdl"
