name: Sync Labels

on:
  push:
    branches:
      - main
    paths:
      - '.github/labels.yml'
      - '.github/workflows/sync-labels.yml'
  workflow_dispatch:

jobs:
  sync-labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Sync labels
        uses: micnncim/action-label-syncer@v1
        with:
          repository: ${{ github.repository }}
          token: ${{ secrets.GITHUB_TOKEN }}
          config_file: .github/labels.yml
          # Optionally you can add these flags:
          # prune: true   # Delete labels not defined in your config file
          # dry_run: true # Preview changes without applying them
